LicenseBreaker: Makefile LicenseBreaker.cpp LicenseBreaker.h ElfUtils.cpp ElfUtils.h SetupView.cpp SetupView.h _APP_
	gcc LicenseBreaker.cpp ElfUtils.cpp SetupView.cpp -lbe -lscreensaver _APP_

_APP_:
	ln -s /system/preferences/ScreenSaver _APP_
